defaults:
  provider: "PROVIDER_NAME"
  model: "MODEL_NAME"

workspace:
  root: "./workspace"
  bolt-db: "./bolt.db"

channels:
  terminal:
    enabled: true

  telegram:
    enabled: true
    bot-token: "BOT_TOKEN"
    allowed-chat-ids:
      - 123456789

providers:
  openai-compatible:
    groq:
      enabled: true
      base-url: "https://api.groq.com/openai/v1"
      chat-api: "/chat/completions"
      models-api: "/models"
      api-key: "API_KEY"
      models:
        - name: "llama-3.1-8b-instant"
    open-router:
      enabled: true
      base-url: "https://openrouter.ai/api/v1"
      chat-api: "/chat/completions"
      models-api: "/models"
      api-key: "API_KEY"
