workspace:
  root: "./workspace"

channels:
  terminal:
    enabled: true

  telegram:
    enabled: true
    bot_token: "BOT_TOKEN"

providers:
  openai_compatible:
    groq:
      enabled: true
      base_url: "https://api.groq.com"
      chat_api: "/openai/v1/chat/completions"
      models_api: "/openai/v1/models"
      api_key: "API_KEY"
      models:
        - name: "llama-3.1-8b-instant"
